### ISSUE TITLE
[Refactor] 코드개선 

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/Weather#14]
## Todo

- [ ] SearchViewController : cityRelay 구독 부분 코드 삭제 (reload)
- [ ] 서버통신 (싱글톤패턴 말고 다른 패턴으로 코드개선 .. 무엇이 있을까??)
- [ ] namespace : enum+struct -> enum으로 개선 (열거형과 구조체의 차이 제대로 알기! 무엇이 더 좋을지 고민하기)
- [ ] 초기값이 길어지는 BehaviorRelay 개선 (따로 모델에서 초기값 관리)
- [ ] 상태코드 분기처리 : ViewController -> ViewModel에서 관리
